image: gcc:latest

before_script:
  # Update the system and add dependencies.
  - apt-get update -qq
  - apt-get -y -qq install build-essential git cmake python-setuptools python-dev libboost-python-dev libglib2.0-dev pkg-config python-pyparsing

  # Compile custom dependencies.
  - DEPS_DIR=$(mktemp -d)
  - pushd $DEPS_DIR

  # Install capstone.
  - git clone https://github.com/aquynh/capstone.git
  - pushd capstone
  - CAPSTONE_ARCHS=arm ./make.sh
  - ./make.sh install
  - pushd bindings/python
  - make
  - make install
  - popd
  - popd

  # Install unicorn.
  - git clone https://github.com/unicorn-engine/unicorn.git
  - pushd unicorn
  - MACOS_UNIVERSAL=yes UNICORN_ARCHS=arm UNICORN_DEBUG=yes ./make.sh
  - ./make.sh install
  - pushd bindings/python
  - make
  - make install
  - popd
  - popd

  # Install darm.
  - git clone https://github.com/jbremer/darm.git
  - pushd darm
  - make
  - cp libdarm.a /usr/lib
  - cp libdarm.so /usr/lib
  - mkdir -p /usr/include/darm
  - cp *.h /usr/include/darm/
  - popd
  - popd

build:
  script:
    # Compile retools sources.
    - mkdir build/
    - pushd build/
    - cmake ..
    - make
    - popd
