language: cpp
dist: trusty

python:
  - "pypy"

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - COMPILER=g++-4.8

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - COMPILER=clang++

install:
  # Update packages.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi

  # Install dependencies.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libboost-python-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install boost-python; fi

  # Install python dependencies.
  - pip install pyparsing

  # Install a modern CMake.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://cmake.org/files/v3.9/cmake-3.9.0-Linux-x86_64.tar.gz  ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xzf cmake-3.9.0-Linux-x86_64.tar.gz                           ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PWD/cmake-3.9.0-Linux-x86_64/bin:$PATH                ;fi

script:
  # Compile retools sources.
  - mkdir build/
  - cd build/
  - export CXX=$COMPILER
  - cmake ..
  - make
